# Generated by Django 4.0.5 on 2022-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('order_id', models.PositiveBigIntegerField()),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rub_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
