# Generated by Django 4.0.5 on 2022-06-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateField(),
        ),
    ]
