# Generated by Django 4.0.5 on 2022-06-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveBigIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
